#!/bin/bash

# Use logger 
logger "Startup script started."

# Write properties to config.properties
logger "Writing to /home/model-server/config.properties..."
mkdir -p /home/model-server/
echo "install_py_dep_per_model=true" >> /home/model-server/config.properties
echo "enable_envvars_config=true" >> /home/model-server/config.properties

# Verify contents and log the output
cat /home/model-server/config.properties | logger

logger "Startup script completed."
